sensor:
  - name: ${bi_10}
    address: 10
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_11}
    address: 11
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_12}
    address: 12
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_13}
    address: 13
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_14}
    address: 14
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_15}
    address: 15
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_16}
    address: 16
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_100}
    address: 100
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_101}
    address: 101
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_102}
    address: 102
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_103}
    address: 103
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_199}
    address: 199
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic

    
number:
  # Changing these will also make you change your yaml files: 
  - name: ${bi_0}
    address: 0
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 1
    max_value: 247
    step: 1
  - name: ${bi_1}
    address: 1
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 0
    max_value: 4
    step: 1
  - name: ${bi_2}
    address: 2
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 0
    max_value: 2
    step: 1
