sensor:
  - name: ${bi_10}
    address: 10
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_11}
    address: 11
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_12}
    address: 12
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_13}
    address: 13
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_14}
    address: 14
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_15}
    address: 15
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_16}
    address: 16
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_100}
    address: 100
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_101}
    address: 101
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_102}
    address: 102
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_103}
    address: 103
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    skip_updates: ${skip_updates.advanced}
    entity_category: diagnostic
  - name: ${bi_199}
    address: 199
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_200}
    address: 200
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_201}
    address: 201
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_202}
    address: 202
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_203}
    address: 203
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_204}
    address: 204
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_205}
    address: 205
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_206}
    address: 206
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_207}
    address: 207
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_208}
    address: 208
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_209}
    address: 209
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_210}
    address: 210
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_211}
    address: 211
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_212}
    address: 212
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_213}
    address: 213
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_214}
    address: 214
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_215}
    address: 215
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_216}
    address: 216
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_217}
    address: 217
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_218}
    address: 218
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_219}
    address: 219
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_220}
    address: 220
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_221}
    address: 221
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_222}
    address: 222
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_223}
    address: 223
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_224}
    address: 224
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_225}
    address: 225
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_226}
    address: 226
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_227}
    address: 227
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_228}
    address: 228
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_229}
    address: 229
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_230}
    address: 230
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_231}
    address: 231
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_232}
    address: 232
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
  - name: ${bi_233}
    address: 233
    value_type: U_WORD
    register_type: holding
    state_class: measurement
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    icon: mdi:information-box
    entity_category: diagnostic
    
number:
  # Changing these will also make you change your yaml files: 
  - name: ${bi_0}
    address: 0
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 1
    max_value: 247
    step: 1
  - name: ${bi_1}
    address: 1
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 0
    max_value: 4
    step: 1
  - name: ${bi_2}
    address: 2
    value_type: U_WORD
    register_type: holding
    platform: modbus_controller
    modbus_controller_id: ${modbus_id}
    skip_updates: ${skip_updates.advanced}
    icon: mdi:cog
    min_value: 0
    max_value: 2
    step: 1
